[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
lib_deps =
    micro_ros_kaia
    kaiaai/LDS @ ^0.8.0
    mike-matera/PID_Timed @ ^1.0.2
    me-no-dev/ESPAsyncWebServer @ ^1.2.3
    adafruit/Adafruit BNO055 @ ^1.6.3
    adafruit/Adafruit INA219 @ ^1.2.1
